version: 2

sources:
  - name: staging
    database: landing
    schema: dbo # Схема, где находятся исходные таблицы
    tables:
      - name: BuyingGroup
      - name: Customer
      - name: CustomerCategory
      - name: CustomerTransaction
      - name: InvoiceLine
      - name: Invoice
      - name: OrderLine
      - name: Order